# Generated by Django 4.2.4 on 2023-09-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createAt',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
